### ISSUE TITLE
Unable to override the ssh connection properties

### ISSUE THREAD

**Issue by alexandruivan** [ansible-community/molecule-openstack#11]
I want to change this:
`-o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey` to this
`-o PreferredAuthentications=publickey`

Because the driver appends the options that I add under ssh_connection_options, I am not able to achieve that result.. Unfortunately, ssh works like this:

```
ssh(1) obtains configuration data from the following sources in the
     following order:

           1.   command-line options
           2.   user's configuration file (~/.ssh/config)
           3.   system-wide configuration file (/etc/ssh/ssh_config)

For each parameter, the first obtained value will be used.

```
How could I have those options changed?

**Comment by nikParasyr** [comment]
Hello. I think this is not molecule-openstack nor molecule behavior. I think it's ansible. Specifically as seen [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py#L641). I'm not sure if overwriting the ansible.cfg will change the `PreferredAuthentications` but i dont think so as they seem hard-coded.

**Comment by nikParasyr** [comment]
Closing the issue as this is outside of molecule-openstack and molecule.
